services:
  sbronzobot:
    container_name: sbronzobot
    environment:
      - PYTHONUNBUFFERED=1

      - SERVICE_PORT=${SERVICE_PORT:-5000}
      - API_TOKEN=${API_TOKEN:-placeholder}
    ports:
      - "8821:${SERVICE_PORT}"
    restart: unless-stopped
    build: .
    pull_policy: build